baseURL = 'https://gustavonazarioperez.github.io/'
languageCode = 'en-us'
title = 'nazario.sh'
theme = "minus40"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  twitter = 'funnyguygus'
  github = 'GustavoNazarioPerez'
  instagram = 'funnyguygus'
  linkedin = 'GustavoNazarioPerez'
  monoDarkIcon = true
  favicon = "favicon.ico"
  buttondownUsername = "nazario"
